root = "Main"

[Main]
type = "QVBoxLayout"
children = ["Toolbar", "MyCanvas"]

[Toolbar]
type = "QHBoxLayout"
children = ["BackLabel", "Status"]

[BackLabel]
type = "QLabel"
text = "FOCUS MODE"

[Status]
type = "QLabel"
text = "Line: $active_line"

[MyCanvas]
type = "vector_canvas"
activeLine = "$active_line"
