root = "Main"

[Main]
type = "QHBoxLayout"
children = ["LeftPanel", "RightPanel"]

[LeftPanel]
type = "QVBoxLayout"
children = ["Title", "MyLines", "PreviewLabel", "MyPreview"]
maxWidth = 200

[Title]
type = "QLabel"
text = "LAYERS"

[RightPanel]
type = "QVBoxLayout"
children = ["MyCanvas"]
